Easylogging files included directly
NOTE: MSVC has a compiler error, and I'm not about to transition to g++ any time soon, so for now, the offending code has been commented out (Yeah, I know. Soon as they push a fix for it, I'll update it)
On lines: 1365, 1448
// COMMENTED OUT DUE TO COMPILER ERROR C4596
     // I STRONGLY SUGGEST RUNNING LIKE HELL FROM THIS CODE